PA_8
Hailey Mueller
Version 1
Spring 2023

In [ ]:
import numpy as np

x=np.array([10,20,30,40])
x

In [82]:
np.square(x)

array([ 100,  400,  900, 1600])

In [83]:
np.add(a,100)

array([[110, 120],
       [130, 140]])

In [84]:
np.multiply(a,5)

array([[ 50, 100],
       [150, 200]])

In [85]:
np.sqrt(a)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [86]:
x=np.array([3,6,9,12,15,18,21,24,27])
x2=np.arange(11,20)
print(x2)
print(x)

[11 12 13 14 15 16 17 18 19]
[ 3  6  9 12 15 18 21 24 27]


In [87]:
np.multiply(x,x2)

array([ 33,  72, 117, 168, 225, 288, 357, 432, 513])

In [88]:
P_1=np.load('process1.npy')
P_1

array([[52, 12, 81,  0, 58]], dtype=int32)

In [89]:
P_2=np.load('process2.npy')
P_2

array([[96,  4, 61, 16, 43]], dtype=int32)

In [90]:
P_3=np.load('process3.npy')
P_3

array([[38, 96, 45, 17, 58]], dtype=int32)

In [91]:
P_4=np.load('process4.npy')
P_4

array([[97, 21, 22, 25,  6]], dtype=int32)

In [92]:
P_5=np.load('process5.npy')
P_5

array([[77,  6, 19,  2, 74]], dtype=int32)

In [93]:
array1=np.vstack([P_1,P_2,P_3,P_4,P_5])
array1

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [94]:
np.mean(array1, axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])